//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat.ChatManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatManager.IChatManager")]
    public interface IChatManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/SendMessage", ReplyAction="http://tempuri.org/IChatManager/SendMessageResponse")]
        void SendMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/SendMessage", ReplyAction="http://tempuri.org/IChatManager/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/GetMessages", ReplyAction="http://tempuri.org/IChatManager/GetMessagesResponse")]
        System.Collections.Generic.List<string> GetMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/GetMessages", ReplyAction="http://tempuri.org/IChatManager/GetMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetMessagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManagerChannel : WebChat.ChatManager.IChatManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatManagerClient : System.ServiceModel.ClientBase<WebChat.ChatManager.IChatManager>, WebChat.ChatManager.IChatManager {
        
        public ChatManagerClient() {
        }
        
        public ChatManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessage(string message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public System.Collections.Generic.List<string> GetMessages() {
            return base.Channel.GetMessages();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetMessagesAsync() {
            return base.Channel.GetMessagesAsync();
        }
    }
}
